### ISSUE TITLE
Mempool unconfirmed balances/actions tracking

### ISSUE THREAD

**Issue by eabz** [olympus-protocol/ogen#223]
### Description

Modify the mempool to track unconfirmed primitives related with its own node wallets and expose the methods for the indexer for light wallets.

- [ ] Track unconfirmed balances
- [ ] Track unconfirmed txs nonces.
- [ ] Track unconfirmed deposits.
- [ ] Track unconfirmed exits.
- [ ] Track unconfirmed partial exits.
